### ISSUE TITLE
JavaAnnotatedElement.getComments() returns unprocessed inline taglets

### ISSUE THREAD

**Issue by kwin** [paul-hammant/qdox#102]
Although `JavaAnnotatedElement.getComments()` (https://github.com/paul-hammant/qdox/blob/37916aed5d39af5a40bcc8eaba70b327ab7a2ba0/src/main/java/com/thoughtworks/qdox/model/JavaAnnotatedElement.java#L57) has a javadoc stating

>  Retrieve the javadoc comment of this annotated element.... but without the doclet tags

it doesn't strip/convert the inline taglets like `{@code }` (https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDFHHBB) or `{@link }` (https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDDIECH)

IMHO those taglets should be converted to plain HTML.

**Comment by kwin** [comment]
Instead of coming up with custom replacements the API/implementation of https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/Taglet.html#isInlineTag-- and https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/Taglet.html#toString-java.util.List-javax.lang.model.element.Element- should be used instead.

Not sure how to reference those for Java 8 and how to get instances of them, though.

**Comment by rfscholte** [comment]
If the comment is used to generate other Java sourcefiles, you don't want these values to be transformed. And HTML is just one possible output. I'm not so sure if and how QDox should do this. For now I would suggest to replace it by using regular expressions.

**Comment by kwin** [comment]
IMHO regular HTML tags are quite common in comments (and those are neither stripped nor processed by getComments()) so I would rather expect getComment() does not return 3 different languages (html, inline taglet, plain text) but only 2 ones (html, plain text).
One would still need to use regular expressions to replace HTML by something else, but at least not two different ones for both `{@code..}` and `<code>`

**Comment by rfscholte** [comment]
The original value needs to be preserved and accessible, so it will be at least 3. The first option that comes to my mind is {{getComment(Transformer)}} to handle this, which even keeps the option open for more transformer implementations.

**Comment by kwin** [comment]
Ok, I agree that for backwards-compatibility reasons we need to keep the current semantics of `getComment()`. Do you see the conversion to plain HTML as part of this library or rather to be implemented in downstream consumers (like https://github.com/apache/maven-plugin-tools/blob/50d5679d5a6f93e014645d1b7c790a96edd2e5bf/maven-plugin-tools-annotations/src/main/java/org/apache/maven/tools/plugin/extractor/annotations/JavaAnnotationsMojoDescriptorExtractor.java#L269)

**Comment by rfscholte** [comment]
Looking at the plugin code, this is again an interesting case. IIRC this is input for the plugin descriptor (XML), which is used for generating the help-goal, so you can call `myplugin:help -Ddetails`. As this is the commandline, you don't want HTML. At the same time there will be a documentantion(report) of this goal, where it has to be HTML. 
Based on that, I think you should keep it as it is, and let Maven Plugin Plugin do the right transformation.

**Comment by kwin** [comment]
Definitely the maven-plugin-tools need to be converted to call `getComment(CommentTransformer)` twice. Once with a `HtmlToTextCommentTransformer` wrapping an `InlineTagletToHtmlCommentTransformer` for generating the descriptor XML and once with only `InlineTagletToHtmlCommentTransformer` for generating HTML for the site report (compare with https://issues.apache.org/jira/browse/MPLUGIN-417). Let me come up with a draft PR as I think such transformers would be beneficial for all consumers of QDox and therefore should rather be contributed here.
