### ISSUE TITLE
Methods with argument types in "java.lang" or primitive argument types cannot be retrieved with getMethodBySignature

### ISSUE THREAD

**Issue by kwin** [paul-hammant/qdox#104]
Given that I have a class with a simple method taking a single argument of type `Integer` (in default import package `java.lang`).

```
class Test {
  public void test(Integer value) {
  }
}
```

Such a method cannot be found with `getMethodBySignature` as the type is incorrectly qualified as nested class and not as class contained in `java.lang`.

**Comment by kwin** [comment]
It seems the underlying issue is in https://github.com/paul-hammant/qdox/blob/37916aed5d39af5a40bcc8eaba70b327ab7a2ba0/src/main/java/com/thoughtworks/qdox/type/TypeResolver.java#L90. It first calls `resolveFromLibrary` which will never return `null` when `SortedClassLibraryBuilder` is used, as that is always containing https://github.com/paul-hammant/qdox/blob/37916aed5d39af5a40bcc8eaba70b327ab7a2ba0/src/main/java/com/thoughtworks/qdox/library/ClassNameLibrary.java#L39. Maybe just switching the order of `resolveInternal` and `resolveFromLibrary` may help in this case.

**Comment by kwin** [comment]
@rfscholte Can you check the attached PR as this issue blocks https://issues.apache.org/jira/browse/MPLUGIN-417? TIA

**Comment by rfscholte** [comment]
> Such a method cannot be found with getMethodBySignature as the type is incorrectly qualified as nested class and not as class contained in java.lang

Are you saying that `getMethodBySignature("java.lang.Integer")` doesn't work?

**Comment by kwin** [comment]
Yes, that is what I am saying (but only if you use `SourceFolderLibrary`). Please see attached test cases.

**Comment by rfscholte** [comment]
LGTM, I've squashed and merged it.
Thanks!
