### ISSUE TITLE
Parse local variables from method content

### ISSUE THREAD

**Issue by kaml8** [paul-hammant/qdox#112]
I am seeking for relations(reference) between different classes.
I found some objects didn't show in `javaMethod.getParameters()` nor in `javaMethod.getReturns()`.

For example, I wrote a `LoginServlet`, which has a function below:
```java
public void service(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, java.io.IOException {

        UserDao userDao = UserDaoImpl.getInstance();
        ...
}
```
Q: How can I get `UserDao` and `UserDaoImpl` through Qdox ?

I can only get rough dependencies by `javaClass.getSource().getImports()`, but it's not enough  to dig **deeper relations**( " **How** does A call B " ).

@paul-hammant 
Will you consider this and take it into your development plan?
I'm looking forward to your solutions or advice.

**Comment by paul-hammant** [comment]
Make a contained **minimal** reproduction of the problem please. That would include a maven pom.xml, and a junit or testng test that fails because of the missing capability. minimal means a very low count of jar dependencies and as much code deleted as possible with the failing test (that should pass) being key to that.

**Comment by paul-hammant** [comment]
Looks good so far.

Can you add an assertion that fails but would pass if the feature/bug would pass, please?

**Comment by kaml8** [comment]
Sorry, it is not a bug but a new suggetted method for interface `JavaMethod`, which is able to achieve a `List<JavaType>` or `List<JavaField>` for local reference type objects from a method, just like what `javaClass.getFields()` did.

JavaParser has mentioned it, here is a quoto from book "javaparser:visited" page 46.

> ![image](https://user-images.githubusercontent.com/62456016/190399152-a17ea636-ee57-4be9-b5b8-65fa02af9123.png)

There is not doubt Qdox is a lightwight lib with great potential in source code parsering.
However, when analysing a method, except argument list and return type, method body also matters.
In method body, those local variables(not primitive) are most import,
they Implied "How does A attach B", I think that is the value of a method.

**Comment by kaml8** [comment]
Project updated. [new test file](https://github.com/kaml8/parse_variables_demo/blob/master/src/test/java/example/ParseTest.java)

I have not writtern a test unit for a method that does't exist before.

The test unit `show_method_local_variables` should be commented out (`@Ignore` doesn't work) if you want to pass the whole test.

**Comment by paul-hammant** [comment]
You don't need this anymore?

**Comment by kaml8** [comment]
I found what I need is to parse callee-called relation([Class A] called [Class B]'s [Method m1] by [instance b]), the issue title may not so appropriate.

You can add this into your developing plan if you want, considering its potential power to excite more valuable parsing ideas.
