### ISSUE TITLE
Duplicated Modifier "interface” when using javaClass.getCodeBlock()

### ISSUE THREAD

**Issue by kaml8** [paul-hammant/qdox#115]
I know that qdox can parse classes in jdk library directly. But some problems occured when I tried this for interfaces.

**These problems only appears for interfaces in jdk library.** Files coded by user seem to work well.

eg:
```java
JavaProjectBuilder builder = new JavaProjectBuilder();
JavaClass javaClass = builder.getClassByName("java.util.Set"); // load class
System.out.println(javaClass.getCodeBlock()); // Q1
System.out.println(javaClass.getTypeParameters()); // Q2
```
Q1:  Duplicated Modifier `interface`  when using `javaClass.getCodeBlock()`

![image](https://user-images.githubusercontent.com/62456016/191867604-e2b6342e-3599-49b3-b2c2-28c6e3a6e71f.png)

---
Q2: Lossing typeParameters when using  when using `javaClass.getCodeBlock()` and `getTypeParameters()`

We all know that `java.util.Set` has a typeParameter `<E>`, but the typeParameter lost when using `javaClass.getCodeBlock()`, and it returns a empty list when using `javaClass.getTypeParameters()`

**Comment by rfscholte** [comment]
Seems the specs are a bit awkward: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/reflect/Modifier.html#toString(int).
So `interface` needs to be filtered out of the modifiers when calling the `getCodeBlock()`
