### ISSUE TITLE
Single type import with fully qualified class name results in incorrect resolved type

### ISSUE THREAD

**Issue by Tunaki** [paul-hammant/qdox#13]
This issue was discovered with the JIRA issue [MPLUGIN-314](https://issues.apache.org/jira/browse/MPLUGIN-314) for the Maven Plugin Plugin, for which it blocks resolution.

Consider the class

```
package parent;

import java.text.SimpleDateFormat;

public class Car {
	private java.text.SimpleDateFormat format;
}
```

which has a single type import of `java.text.SimpleDateFormat` and the field `format` has the same type `java.text.SimpleDateFormat` as the import. (Note that the import is actually unused). The following code:

```
JavaProjectBuilder builder = new JavaProjectBuilder();
builder.addSource(new File(".../parent/Car.java"));
JavaField field = builder.getClassByName("parent.Car").getFieldByName("format");
System.out.println(field.getType());
```

prints `java$text$SimpleDateFormat`, instead of the expected `java.text.SimpleDateFormat`. Since `maven-plugin-plugin` [relies on that](https://github.com/apache/maven-plugin-tools/blob/maven-plugin-tools-3.5/maven-plugin-tools-java/src/main/java/org/apache/maven/tools/plugin/extractor/javadoc/JavaJavadocMojoDescriptorExtractor.java#L419), it then gets an incorrect type. The canonical name of the field is correctly `java.text.SimpleDateFormat`.

Is this expected?

A quick fix I've tested is modifying [`DefaultJavaSource#resolveImportedType`](https://github.com/paul-hammant/qdox/blob/qdox-2.0-M4/src/main/java/com/thoughtworks/qdox/model/impl/DefaultJavaSource.java#L257) method, and have

```
String candidateName = imprt.equals(importSpec) ? imprt
		: imprt.substring(0, imprt.length() - importSpec.length()) + typeName;
```

which considers a candidate name of exactly the import type when the field's type and the import are the same, instead of 

```
String candidateName = imprt.substring(0, imprt.length() - importSpec.length()) + typeName;
```

That change broke no tests (both UT and IT).

**Comment by rfscholte** [comment]
It should have been `java.text.SimpleDateFormat`, so it is indeed a bug. I'll have a look at it.
