### ISSUE TITLE
parsing of java source not ignoring commented code

### ISSUE THREAD

**Issue by zoth** [paul-hammant/qdox#16]
This looks like a bug to me or am I doing something wrong?
I'm using version 2.0-M5 and java version 7.

Source files:
public class ZothParent 
{
	private String name;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
}

public class ZothChild //extends ZothParent
{
	private int age;

	public int getAge() {
		return age;
	}

	public void setAge(int age) {
		this.age = age;
	}
}

parsing code:
JavaProjectBuilder builder = new JavaProjectBuilder();
builder.addSourceFolder(new File("src/main/java"));
JavaClass zothClass = builder.getClassByName("play.ZothChild");
		
for(BeanProperty bp: zothClass.getBeanProperties(true)){
	System.out.println(bp.getName());
}

output:
age
name
class

Because the ZothChild extends is commented out the output should not include "name".

**Comment by rfscholte** [comment]
Confirmed and fixed
