### ISSUE TITLE
The "JavaWildcardType" interface should expose the bound and its type

### ISSUE THREAD

**Issue by negora** [paul-hammant/qdox#178]
I think the `JavaWildcardType` interface should expose the bound of the wildcard and its type (*extends* or *super*).

The default implementation, `DefaultJavaWildcardType`, already stores that information. However, this class doesn't expose that data either. Is there anything that I'm overlooking?

Thank you in advance.

**Comment by negora** [comment]
Before creating my ticket, I had looked for open issues related to this topic. Now I've searched for closed ones and have found the issue  #133. There, you seem to have modified `JavaWildcardType` to expose the bounds. However, I've the GitHub repository synchronized and can't find that methods in the `JavaWildcardType` interface. Is this change in a branch different from `master`?

Thank you.

**Comment by rfscholte** [comment]
I've merged the pull request
