### ISSUE TITLE
Why can't I find the com.thoughtworks.qdox.parser.impl.JFlexLexer class from the master branch?

### ISSUE THREAD

**Issue by tianmingxing** [paul-hammant/qdox#199]
![屏幕截图 2023-12-23 111948](https://github.com/paul-hammant/qdox/assets/5615719/154c34e3-25ca-4e1e-b4ee-3b6dac9a27d4)

**Comment by rfscholte** [comment]
With [these Maven plugins](https://github.com/paul-hammant/qdox/blob/master/pom.xml#L224-L290) sourcecode is generated
