### ISSUE TITLE
SuperClass Field Types are always canonical

### ISSUE THREAD

**Issue by fkreis** [paul-hammant/qdox#2]
If I access the type of a super type’s field like

`qdox.model.BeanProperty beanProperty = javaClass.getBeanProperties(true).get(anyIndex);`
`qdox.model.JavaType fieldType = beanProperty.getType();`

and call

`fieldType.getGenericValue()`
`fieldType.getGenericCanonicalName()`

in both cases the answer is the canonical name (e.g. java.lang.Long). But for the first call I expect the simple name Long. If I call these methods on non-supertype fields it works as expected.

**Comment by rfscholte** [comment]
This is the javadoc of JavaType.getGenericValue(), which means it works as expected:

    /**
     * The FQN representation of an Object for code usage
     * This implementation ignores generics
     *
     * Some examples how Objects will be translated
     * <pre>
     * Object > java.lang.object
     * java.util.List<T> > java.util.List
     * ? > ?
     * T > T
     * anypackage.Outer.Inner > anypackage.Outer.Inner
     * </pre>

     * @since 1.8
     * @return generic type representation for code usage 
     */
    public String getGenericValue()
