### ISSUE TITLE
com.thoughtworks.qdox.parser.ParseException

### ISSUE THREAD

**Issue by fuxiangxu** [paul-hammant/qdox#37]
com.thoughtworks.qdox.parser.ParseException: syntax error @[457,38] in UNKNOWN SOURCE
private void calPayInfo(@Nullable PayInfo payInfo)
version 1.6

**Comment by rfscholte** [comment]
This is not really a clear testcase, but assuming the `private void calPayInfo(@nullable PayInfo payInfo)` was causing the ParseException in QDox-1.6, it doesn't with the latest QDox-2. Upgrading should be the solution.
