### ISSUE TITLE
missing methods

### ISSUE THREAD

**Issue by ramsestom** [paul-hammant/qdox#41]
Unlike what is stated in the readme file, JavaType.isArray() do not exist.
So how can I know if a parametter of a method is an array or not? 
Because actually the example:
```
JavaMethod m = cls.getMethods()[0];
JavaParameter o = m.getParameters()[1];
boolean oArray = o.getType().isArray(); // true
```
won't work as `.isArray()` do not exist for JavaType...

**Comment by rfscholte** [comment]
Starting with QDox2 the model reflects more the Java API. Based on that, there's no isArray() for [Type](https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/Type.html). Instead you should use the JavaClass, just like [Class#isArray](https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#isArray--)
Documentation should be updated...
