### ISSUE TITLE
Wrong full names.

### ISSUE THREAD

**Issue by Heaminator** [paul-hammant/qdox#53]
I wanted to get the full name of an annotation. But sometimes it shows the wrong full name:
`package bla;
import java.lang.*;

@Deprecated
public class Consumer {	
}`

This is my first example. After the method `System.out.println(sourceannotation.getFullyQualifiedName());` (after getting Class of the annotation) I am getting this: 

> java.lang.Deprecated

Alright: Second try
`package bla;
import org.mongodb.morphia.annotations.*;

@Entity(value = "world", noClassnameStored = true)
public class Consumer {	
}`

But doing the same thing like before I am only getting this: 

> Entity

and this is wrong! I am awaiting this:

> org.mongodb.morphia.annotations.Entity

**Comment by rfscholte** [comment]
Be sure that `org.mongodb.morphia.annotations.Entity` is accessible via the `JavaProjectBuilder`. Can you create a small project to reproduce your issue?

**Comment by Heaminator** [comment]
I am doing this (I show only the methods, otherwise it will be too big)
`JavaProjectBuilder builder = new JavaProjectBuilder();
JavaSource src = builder.addSource(new FileReader("Consumer.java"));
List<JavaClass> classes = src.getClasses();
for(JavaClass klasse : classes) {
 List<JavaAnnotation> classannotations = klasse.getAnnotations();
 for(JavaAnnotation classannotation : classannotations) {
  JavaClass sourceannotation = classannotation.getType();
  System.out.println(sourceannotation.getFullyQualifiedName());
}`

And like the comments before it shows these.

**Comment by rfscholte** [comment]
You have to add `org.mongodb.morphia.annotations.Entity` to, either as source or class.

**Comment by Heaminator** [comment]
I can't do this, becuase this class is in a jar file!
Btw. I found out that `org.mongodb.morphia.annotations.*` is in `typeResolver`. But it can't get it because `fullName` is not NULL.

**Comment by Heaminator** [comment]
Ah okay... now its working - thanks
