### ISSUE TITLE
 NoClassDefFoundError

### ISSUE THREAD

**Issue by SadTomato** [paul-hammant/qdox#55]
Got this exception trying to parse a nested class with next kind of structure:
```
public static class A {
    private int someValue = 0;
    public A doSomething(int val) {
        this.someValue = val;
        return this;
    }
}
```
The problem is that I cannot parse it. My first thought was that it is connected with a reflection (class A returns class A). Am I wrong?

**Comment by rfscholte** [comment]
Following code works as expected, no Exception:

    public void testMe() throws Exception {
        String source = "public static class A {\r\n" + 
            "    private int someValue = 0;\r\n" + 
            "    public A doSomething(int val) {\r\n" + 
            "        this.someValue = val;\r\n" + 
            "        return this;\r\n" + 
            "    }\r\n" + 
            "}";
        
        new JavaProjectBuilder().addSource( new StringReader( source ) );
    }

Please provide more details.
