### ISSUE TITLE
Cannot load interface class from jar

### ISSUE THREAD

**Issue by shalousun** [paul-hammant/qdox#64]
qdox version: 2.0.0

I defined an interface class and packaged the interface class into a jar and published it to the maven repository, and then I depended on it in the project. I can't get this interface class through qdox, but for classes that are not interfaces, qdox can be loaded.
````
public interface IMessage {

    /**
     * error code
     *
     * @return String
     */
    String getCode();

    /**
     * error message
     *
     * @return String
     */
    String getMessage();
}
````

Thank you very much for the qdox project. I use it to develop an open source restful api document generation tool [smart-doc](https://github.com/shalousun/smart-doc). And it is loved by a lot of developers in China. The above problem is that I need to analyze some interface class definitions to generate api documents when developing tools, but I cannot get the interface type class through qdox.

**Comment by rfscholte** [comment]
Can you provide a code sample where QDox is used to read the interface?

**Comment by shalousun** [comment]
sample is like this.
```
JavaProjectBuilder javaProjectBuilder = new JavaProjectBuilder();
 javaProjectBuilder.addSourceTree("src/main/java");
JavaClass cls = javaProjectBuilder.getClassByName("interface name from jar");
// cls is null
JavaClass cls = javaProjectBuilder.getClassByName("JavaBean name from jar");
// cls is not null
```
I want to get the information of my defined  interface.

**Comment by rfscholte** [comment]
I wrote a unittest, it shows it works for both classes and interfaces.
