### ISSUE TITLE
how to skip file which parse failed?

### ISSUE THREAD

**Issue by dezhonger** [paul-hammant/qdox#66]
A java file with all commnet, such as
`
//package com.y2020.m04.d11;
//
//public class A {
////    int a;
//}
`
how to skip this file parse

**Comment by Ziyear** [comment]
```java
        JavaProjectBuilder builder = new JavaProjectBuilder();
        builder.setErrorHandler((e) -> log.warn(e.getMessage()));
```
I hope I can help you
Of course, you can change the print log to your arbitrary processing logic

**Comment by rfscholte** [comment]
If it is a valid Java source file, there should be no issue. The `JavaProjectBuilder` only has methods to add sourcefiles.
