### ISSUE TITLE
how to get JavaClass from DefaultJavaType in a simple way

### ISSUE THREAD

**Issue by DingouerFish** [paul-hammant/qdox#78]
I noticed the DefaultJavaType.resolveRealClass can do this, but it is private

**Comment by rfscholte** [comment]
Your code should not rely on the implementation, but on the interface, i.e. `JavaType`.

**Comment by DingouerFish** [comment]
> Your code should not rely on the implementation, but on the interface, i.e. `JavaType`.
okay,so how to get JavaClass from JavaType

**Comment by rfscholte** [comment]
QDox reflects the Java model, and just like https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Type.html you can't do that.

**Comment by DingouerFish** [comment]
> QDox reflects the Java model, and just like https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Type.html you can't do that.

but there is indeed a private method  DefaultJavaType.resolveRealClass can do this,  so if I have a JavaType, is there any simple way to create the corresponding JavaClass? my code is like this:
DefaultJavaType.getSource().getClassByName，just a a little ugly, maybe resolveRealClass should be public

**Comment by rfscholte** [comment]
That's not going ot happen: Class implements Type, but that doesn't mean that every Type is a Class. Exposing more than the Java API might cause trouble in the future.

**Comment by DingouerFish** [comment]
> That's not going ot happen: Class implements Type, but that doesn't mean that every Type is a Class. Exposing more than the Java API might cause trouble in the future.

well,here is my case:
```java

public void func(Test p) {
        return null;
}

public class Test<T> {
	private T name;
	private int age;
}

```

I want to get the  formal paramter information of the  method func's paramter p, p is a DefaultJavaParameterizedType, which is a type ,so I need to get it's corresponding JavaClass, which contains the generic information, could you show me an easy way to achieve this ?

**Comment by rfscholte** [comment]
You're saying T is a [JavaParameterizedType](https://github.com/paul-hammant/qdox/blob/master/src/main/java/com/thoughtworks/qdox/model/JavaParameterizedType.java) , which should reflect https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/ParameterizedType.html but again these are Types, not Classes.
I'd suggest to first try it with Java reflection. If you can't do it like that, it's not going to work with QDox.
