### ISSUE TITLE
Parse bug, DefaultJavaClass fails to understand [] as isArray()

### ISSUE THREAD

**Issue by masta99wrfvsHsa** [paul-hammant/qdox#89]
testcode>
com.thoughtworks.qdox.model.impl.DefaultJavaClass innertype=new com.thoughtworks.qdox.model.impl.DefaultJavaClass("String[]");
System.out.println(type);//debug use
		System.out.println(defjavatype.isArray());//debug use

output>
String[]
false

**Comment by rfscholte** [comment]
Even though these classes are public, there's often no reason to create instances like this.
Apart from that, you should not use DefaultJavaClass, but DefaultJavaType instead, where you can specify the dimensions.
