### ISSUE TITLE
Official QDox repo? And stable release upcoming?

### ISSUE THREAD

**Issue by lennartj** [paul-hammant/qdox#9]
Hello folks.

I wonder if this repo (i.e. https://github.com/paul-hammant/qdox) is the official QDox repo?

And - if so - how we are standing in regards to a 2.0 (as opposed to a milestone) release?

**Comment by rfscholte** [comment]
This is indeed the official repo for QDox. I haven't had a look at this project for a while, probably need should have a look at Java9 as well to see if it still fits.
