### ISSUE TITLE
Seems QDox 2.0.1 has issue parsing parameter names named "recordList"

### ISSUE THREAD

**Issue by ghzengqy568** [paul-hammant/qdox#99]
Seems QDox 2.0.1 has issue parsing parameter names named "recordList"

**Comment by rfscholte** [comment]
should be fixed with https://github.com/paul-hammant/qdox/commit/c887457779b8b3b41a7226147bcd0bd9163161ff. Can you verify?

**Comment by ghzengqy568** [comment]
> Can you verify

sure.

**Comment by ghzengqy568** [comment]
> should be fixed with [c887457](https://github.com/paul-hammant/qdox/commit/c887457779b8b3b41a7226147bcd0bd9163161ff). Can you verify?

record is ok. But recordList still has the same problem

**Comment by rfscholte** [comment]
Found the problem, should be better now.
